# ###*B*###
#
# ERIKA Enterprise - a tiny RTOS for small microcontrollers
# 
# Copyright (C) 2002-2018 Evidence Srl
# 
# This file is part of ERIKA Enterprise.
# 
# See LICENSE file.
#
# ###*E*###

############################################################################
#
# This file is generated by RT-Druid.
# Please do not modify it.
#
############################################################################

############################################################################
#
# User options
#
############################################################################
OS_EE_OPT += OSEE_DEBUG
OS_EE_OPT += OS_EE_APPL_BUILD_DEBUG
OS_EE_OPT += OS_EE_BUILD_DEBUG


############################################################################
#
# Automatic options
#
############################################################################
OS_EE_OPT += OSEE_ARCH_TRICORE
OS_EE_OPT += OSEE_CPU_CLOCK (200000000U)
OS_EE_OPT += OSEE_HAS_ALARMS
OS_EE_OPT += OSEE_HAS_AUTOSTART_TASK
OS_EE_OPT += OSEE_HAS_AUTOSTART_TRIGGER
OS_EE_OPT += OSEE_HAS_COUNTERS
OS_EE_OPT += OSEE_HAS_EVENTS
OS_EE_OPT += OSEE_HAS_RESOURCES
OS_EE_OPT += OSEE_HAS_STARTUPHOOK
OS_EE_OPT += OSEE_HAS_SYSTEM_TIMER
OS_EE_OPT += OSEE_ISR2_MAX_HW_ASM_PRIO 5
OS_EE_OPT += OSEE_ISR2_MAX_PRIO (132U)
OS_EE_OPT += OSEE_MULTI_STACK
OS_EE_OPT += OSEE_OC_ECC1
OS_EE_OPT += OSEE_SINGLE_ACTIVATION
OS_EE_OPT += OSEE_TC_CORE0_ISR_MAX_PRIO  (5U)
OS_EE_OPT += OSEE_TC_TC27X
OS_EE_OPT += OS_EE_GCC
OS_EE_OPT += OS_EE_KERNEL_OSEK
OS_EE_OPT += OS_EE_RTD_BUILD_ENV_CYGWIN
OS_EE_OPT += OS_EE_RTD_DISABLE_OS_EE_OPT_DEFINES




############################################################################
#
# Path check and conversion
#
############################################################################
-include $(OS_EE_BASE_DIR)/mk/ee_path_helper.mk
-include $(ERIKA_FILES)/mk/ee_path_helper.mk

############################################################################
#
# HighTec GCC Compiler path
#
############################################################################
$(eval $(call check_and_set_cygwin_compiler_path,BINDIR,C:\HighTec\toolchains\tricore\v4.9.3.0-infineon-1.0/bin/))


OSEE_TRICORE_MCU    := tc27x
OSEE_TRICORE_MCU_UC := TC27X
OSEE_TRICORE_STEP := D
OPT_CPU := -mcpu=tc27xx

export OPT_CPU 

export OSEE_TRICORE_MCU
export OSEE_TRICORE_MCU_UC


############################################################################
#
# Flags
#
############################################################################
CFLAGS  +=
CFLAGS  += -fno-common -O2
CFLAGS  += -fgcse-after-reload -ffast-math
CFLAGS  += -funswitch-loops -fpredictive-commoning
CFLAGS  += -ftree-vectorize -fipa-cp-clone
CFLAGS  += -fpeel-loops -fmove-loop-invariants
CFLAGS  += -frename-registers -fira-algorithm=priority
CFLAGS  += -g3 -W -Wall -Wextra -Wdiv-by-zero
CFLAGS  += -Warray-bounds -Wcast-align -Wignored-qualifiers
CFLAGS  +=  -Wformat -Wformat-security -fshort-double -mcpu=tc27xx -mversion-info -std=c99
export CFLAGS

ASFLAGS +=
export ASFLAGS

LDFLAGS +=
export LDFLAGS

LDDEPS  +=
export LDDEPS

LIBS    +=
export LIBS


############################################################################
#
# Sources
#
############################################################################
OS_EE_CFG_SRCS +=
OS_EE_CFG_SRCS += ee_oscfg.c
export OS_EE_CFG_SRCS


############################################################################
#
# End
#
############################################################################

